using System.Reflection;
using System.Text;
using System.Text.Json;
using DotnetToTypescript.Typescript;

namespace DotnetToTypescript.Testing.Robustness;

public static class ApiCatalogBuilder
{
    private const int MaxGraphDepth = 3;
    private static readonly NullabilityInfoContext NullabilityContext = new();

    public static string BuildCatalogModule(
        IReadOnlyList<(string GlobalName, Type Type)> globals,
        bool preserveCase)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/**");
        sb.AppendLine(" * Reflection-driven API catalog for robustness testing.");
        sb.AppendLine(" * Generated by dotnet-to-typescript — do not edit by hand.");
        sb.AppendLine(" */");
        sb.AppendLine();
        sb.AppendLine("export const apiCatalog = {");
        sb.AppendLine("  globals: [");

        foreach (var (globalName, type) in globals.OrderBy(g => g.GlobalName, StringComparer.Ordinal))
        {
            AppendGlobal(sb, globalName, type, preserveCase, indent: 2);
        }

        sb.AppendLine("  ],");
        sb.AppendLine("};");
        sb.AppendLine();
        return sb.ToString();
    }

    private static void AppendGlobal(
        StringBuilder sb,
        string globalName,
        Type type,
        bool preserveCase,
        int indent)
    {
        var pad = Pad(indent);
        var pad2 = Pad(indent + 1);

        sb.AppendLine($"{pad}{{");
        sb.AppendLine($"{pad2}name: {JsString(globalName)},");
        sb.AppendLine($"{pad2}typeName: {JsString(type.Name)},");
        sb.AppendLine($"{pad2}methods: [");

        foreach (var method in ScriptMemberInspector.GetMethods(type))
        {
            AppendMethod(sb, globalName, method, preserveCase, indent + 2);
        }

        sb.AppendLine($"{pad2}],");
        sb.AppendLine($"{pad2}properties: [");

        foreach (var prop in ScriptMemberInspector.GetProperties(type))
        {
            AppendPropertyNode(sb, prop, ScriptMemberInspector.FormatName(prop.Name, preserveCase), preserveCase, indent + 2);
        }

        sb.AppendLine($"{pad2}],");
        sb.AppendLine($"{pad}}},");
    }

    private static void AppendMethod(
        StringBuilder sb,
        string globalName,
        MethodInfo method,
        bool preserveCase,
        int indent)
    {
        var pad = Pad(indent);
        var pad2 = Pad(indent + 1);
        var name = ScriptMemberInspector.FormatName(method.Name, preserveCase);
        var path = $"{globalName}.{name}";
        var returnType = method.ReturnType;
        var kind = ScriptMemberInspector.GetReturnKind(returnType);
        var isAsync = ScriptMemberInspector.IsAsyncType(returnType);
        var defaultExpr = DefaultValueFactory.GetBaselineReturnExpression(returnType, preserveCase);

        sb.AppendLine($"{pad}{{");
        sb.AppendLine($"{pad2}name: {JsString(name)},");
        sb.AppendLine($"{pad2}path: {JsString(path)},");
        sb.AppendLine($"{pad2}returnKind: {JsString(kind)},");
        sb.AppendLine($"{pad2}isAsync: {JsBool(isAsync)},");
        sb.AppendLine($"{pad2}isVoid: {JsBool(ScriptMemberInspector.IsVoidType(returnType))},");
        sb.AppendLine($"{pad2}isReferenceReturn: {JsBool(ScriptMemberInspector.IsReferenceReturnType(returnType))},");
        sb.AppendLine($"{pad2}isCollection: {JsBool(ScriptMemberInspector.IsCollectionType(returnType))},");
        sb.AppendLine($"{pad2}isDictionary: {JsBool(ScriptMemberInspector.IsDictionaryType(returnType))},");
        sb.AppendLine($"{pad2}isBoolean: {JsBool(ScriptMemberInspector.IsBooleanType(returnType))},");
        sb.AppendLine($"{pad2}isNumeric: {JsBool(ScriptMemberInspector.IsNumericType(returnType))},");
        sb.AppendLine($"{pad2}isString: {JsBool(ScriptMemberInspector.IsStringType(returnType))},");
        sb.AppendLine($"{pad2}isObject: {JsBool(kind == "object")},");
        sb.AppendLine($"{pad2}defaultReturnExpression: {JsString(defaultExpr)},");
        sb.Append($"{pad2}returnGraph: ");
        AppendTypeGraph(sb, returnType, preserveCase, depth: 0, visited: [], indent + 1);
        sb.AppendLine(",");
        sb.AppendLine($"{pad}}},");
    }

    private static void AppendPropertyNode(
        StringBuilder sb,
        PropertyInfo prop,
        string name,
        bool preserveCase,
        int indent)
    {
        var pad = Pad(indent);
        var pad2 = Pad(indent + 1);
        var kind = ScriptMemberInspector.GetReturnKind(prop.PropertyType);

        sb.AppendLine($"{pad}{{");
        sb.AppendLine($"{pad2}name: {JsString(name)},");
        sb.AppendLine($"{pad2}path: {JsString(name)},");
        sb.AppendLine($"{pad2}kind: {JsString(kind)},");
        sb.AppendLine($"{pad2}isOptional: {JsBool(IsOptionalProperty(prop))},");
        sb.AppendLine($"{pad2}isCollection: {JsBool(ScriptMemberInspector.IsCollectionType(prop.PropertyType))},");
        sb.AppendLine($"{pad2}isDictionary: {JsBool(ScriptMemberInspector.IsDictionaryType(prop.PropertyType))},");
        sb.AppendLine($"{pad2}isBoolean: {JsBool(ScriptMemberInspector.IsBooleanType(prop.PropertyType))},");
        sb.AppendLine($"{pad2}isNumeric: {JsBool(ScriptMemberInspector.IsNumericType(prop.PropertyType))},");
        sb.AppendLine($"{pad2}isString: {JsBool(ScriptMemberInspector.IsStringType(prop.PropertyType))},");
        sb.AppendLine($"{pad2}isObject: {JsBool(kind == "object")},");
        sb.AppendLine($"{pad2}isReference: {JsBool(ScriptMemberInspector.IsReferenceReturnType(prop.PropertyType))},");
        sb.AppendLine($"{pad}}},");
    }

    private static void AppendTypeGraph(
        StringBuilder sb,
        Type type,
        bool preserveCase,
        int depth,
        HashSet<Type> visited,
        int indent)
    {
        var unwrapped = ScriptMemberInspector.UnwrapTask(Nullable.GetUnderlyingType(type) ?? type);
        var kind = ScriptMemberInspector.GetReturnKind(type);

        if (kind != "object" || depth >= MaxGraphDepth || !visited.Add(unwrapped))
        {
            sb.Append($"{{ kind: {JsString(kind)}, properties: [] }}");
            return;
        }

        try
        {
            var pad = Pad(indent);
            var pad2 = Pad(indent + 1);
            sb.AppendLine("{");
            sb.AppendLine($"{pad2}kind: {JsString(kind)},");
            sb.AppendLine($"{pad2}properties: [");

            foreach (var prop in ScriptMemberInspector.GetProperties(unwrapped))
            {
                var name = ScriptMemberInspector.FormatName(prop.Name, preserveCase);
                var propKind = ScriptMemberInspector.GetReturnKind(prop.PropertyType);
                var propPad = Pad(indent + 2);
                var propPad2 = Pad(indent + 3);

                sb.AppendLine($"{propPad}{{");
                sb.AppendLine($"{propPad2}name: {JsString(name)},");
                sb.AppendLine($"{propPad2}path: {JsString(name)},");
                sb.AppendLine($"{propPad2}kind: {JsString(propKind)},");
                sb.AppendLine($"{propPad2}isOptional: {JsBool(IsOptionalProperty(prop))},");
                sb.AppendLine($"{propPad2}isCollection: {JsBool(ScriptMemberInspector.IsCollectionType(prop.PropertyType))},");
                sb.AppendLine($"{propPad2}isDictionary: {JsBool(ScriptMemberInspector.IsDictionaryType(prop.PropertyType))},");
                sb.AppendLine($"{propPad2}isBoolean: {JsBool(ScriptMemberInspector.IsBooleanType(prop.PropertyType))},");
                sb.AppendLine($"{propPad2}isNumeric: {JsBool(ScriptMemberInspector.IsNumericType(prop.PropertyType))},");
                sb.AppendLine($"{propPad2}isString: {JsBool(ScriptMemberInspector.IsStringType(prop.PropertyType))},");
                sb.AppendLine($"{propPad2}isObject: {JsBool(propKind == "object")},");
                sb.AppendLine($"{propPad2}isReference: {JsBool(ScriptMemberInspector.IsReferenceReturnType(prop.PropertyType))},");
                sb.Append($"{propPad2}graph: ");
                AppendTypeGraph(sb, prop.PropertyType, preserveCase, depth + 1, visited, indent + 3);
                sb.AppendLine(",");
                sb.AppendLine($"{propPad}}},");
            }

            sb.Append($"{pad2}],");
            sb.AppendLine();
            sb.Append($"{pad}}}");
        }
        finally
        {
            visited.Remove(unwrapped);
        }
    }

    private static bool IsOptionalProperty(PropertyInfo prop)
    {
        if (Nullable.GetUnderlyingType(prop.PropertyType) != null)
            return true;

        try
        {
            var info = NullabilityContext.Create(prop);
            return info.ReadState == NullabilityState.Nullable;
        }
        catch (Exception)
        {
            return !prop.PropertyType.IsValueType;
        }
    }

    private static string Pad(int indent) => new(' ', indent * 2);

    private static string JsBool(bool value) => value ? "true" : "false";

    private static string JsString(string value) =>
        JsonSerializer.Serialize(value);
}
