name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore Source/DotnetToTypescript.sln
      
    - name: Build
      run: dotnet build Source/DotnetToTypescript.sln --no-restore
      
    - name: Test
      run: dotnet test Source/DotnetToTypescript.sln --no-build --verbosity normal